---
- hosts: all
  user: vagrant
  sudo: True
  roles:
    - common

- hosts: dse
  user: vagrant
  sudo: True
  roles:
    - dse-install

- hosts: opscenter
  user: vagrant
  sudo: True
  roles:
    - opscenter

- hosts: sparkmasters
  user: vagrant
  sudo: True
  roles:
    - spark-cloudera-master

- hosts: sparkworkers
  user: vagrant
  sudo: True
  roles:
    - spark-cloudera-worker

- hosts: sparkhistory
  user: vagrant
  sudo: True
  roles:
   - spark-cloudera-history

- hosts: sparkjobserver
  user: vagrant
  sudo: True
  roles:
    - spark-jobserver

- hosts: graphite
  user: vagrant
  sudo: True
  roles:
    - { role: install-graphite, tags: [ 'install-graphite'] }

- hosts: grafana
  user: vagrant
  sudo: True
  roles:
     - {role: install-grafana, tags: ['install-grafana']}