---
- hosts: all
  user: vagrant
  sudo: True
  roles:
    - common

# DataStax Enterprise
- hosts: dse
  user: vagrant
  sudo: True
  roles:
    - dse-install

# OpsCenter
- hosts: opscenter
  user: vagrant
  sudo: True
  roles:
    - opscenter

# Add Spark
- hosts: sparkmasters
  user: vagrant
  sudo: True
  roles:
    - spark_master
    - spark_history

- hosts: sparkworkers
  user: vagrant
  sudo: True
  roles:
    - spark_workers

