---
- hosts: all
  user: vagrant
  sudo: True
  roles:
    - common

# DataStax Enterprise
- hosts: dse
  user: vagrant
  sudo: True
  roles:
    - dse-install

# OpsCenter
- hosts: opscenter
  user: vagrant
  sudo: True
  roles:
    - opscenter

- hosts: sparkmasters
  user: vagrant
  sudo: True
  roles:
    - spark_master

- hosts: sparkworkers
  user: vagrant
  sudo: True
  roles:
    - spark_workers

- hosts: sparkhistory
  user: vagrant
  sudo: True
  roles:
   - spark_history

- hosts: sparkjobserver
  user: vagrant
  sudo: True
  roles:
    - spark_jobserver

- hosts: graphite
  user: vagrant
  sudo: True
  roles:
    - { role: install-graphite, tags: [ 'install-graphite'] }

- hosts: grafana
  user: vagrant
  sudo: True
  roles:
     - {role: install-grafana, tags: ['install-grafana']}