---
- hosts: all
  user: vagrant
  sudo: True
  roles:
    - common

# DataStax Enterprise
- hosts: dse
  user: vagrant
  sudo: True
  roles:
    - dse-install

# OpsCenter
- hosts: opscenter
  user: vagrant
  sudo: True
  roles:
    - opscenter

- hosts: sparkmasters
  user: vagrant
  sudo: True
  roles:
    - spark_master
    - spark_history
- hosts: graphite
  roles:

- hosts: sparkworkers
  user: vagrant
  sudo: True
  roles:
    - spark_workers

- hosts: sparkjobserver
  user: vagrant
  sudo: True
  roles:
    - spark_jobserver

# Graphite stuff
#https://github.com/jsmartin/ansible-graphite
- hosts: graphite
  user: vagrant
  sudo: True
  roles:
    - { role: ansible-graphite, tags: [ 'install-graphite'] }

- hosts: grafana
  user: vagrant
  sudo: True
  roles:
     - {role: ansible-grafana-package, tags: ['install-ansible-grafana-package']}