---
# file: roles/spark/tasks/main.yml

- name: copy init file
  template: src=spark-worker dest=/etc/init.d/spark-worker owner=root group=root mode=755
  tags:
    - spark

- name: restart worker
  service: name=spark-worker state=restarted
  tags:
    - spark
    - start-spark-worker
