---
# file: roles/spark/tasks/main.yml

- name: copy init file
  template: src=spark-history dest=/etc/init.d/spark-history owner=root group=root mode=755
  tags:
    - spark
    - start-spark-history

- name: create log direcory
  file: path=/tmp/spark-events state=directory mode=777
  tags:
      - spark
      - start-spark-history

- name: start spark history
  service: name=spark-history state=restarted
  tags:
    - spark
    - start-spark-history

