---
# file: roles/spark/tasks/main.yml

- name: copy init file
  template: src=spark-history.sh dest=/etc/init.d/spark-history owner=root group=root mode=755
  tags:
    - spark
    - start-spark-history

- name: create spark-history server log dir
  file: path={{ historyserver.serverLogLocation }} state=directory

- name: start spark history
  service: name=spark-history state=restarted
  tags:
    - spark
    - start-spark-history

