- name: installing datastax enterprise
  apt: pkg=dse-full state=installed update-cache=yes
  register: dse

- name: creating jna symlink
  shell: ln -s /usr/share/java/jna.jar /usr/share/dse/cassandra/lib || true

- name: configuring datastax enterprise
  template: src=cassandra.yaml dest=/etc/dse/cassandra/cassandra.yaml

- name: Adding customized cassandra setting
  template: src=cassandra-env.sh dest=/etc/dse/cassandra/cassandra-env.sh

- name: starting dse
  service: name=dse enabled=yes state=started
